### ISSUE TITLE
more [WIP problems]: manure mixer

### ISSUE THREAD

**Issue by macks2008** [GenDeathrow/Hatchery#112]
doesn't seem to work very well with single-use fluid buckets such as water chicken eggs. It moves a stack of zero into the output slot and allows things like hoppers (or in my case, Ender IO fluid tanks) to pull the rest of the stack out. You may want to make sure your other fluid-accepting machines (e.g. methane digester) don't do the same with similar fluid containers (e.g. I should be able to put a forestry capsule of liquid fertilizer in a digester generator without it producing an empty stack and letting things pull from the input slot. Don't let other machines pull valid inputs!)
side note: will fertilized dirt ever be made to decay back into dirt? Because otherwise my  stacks upon stacks of manure blocks are only good for energy. I don't mind having lots of energy, but it feels a tiny bit OP.

**Comment by Syndaryl** [comment]
An idea re fertilized dirt: Have it revert to standard farmland after a set number of "bone-meals" - 64, 32, 128, whatever, make it configurable.

**Comment by GenDeathrow** [comment]
Actually thanks for bringing this up @macks2008. I forgot I had this on my list of to-do stuff. I knew the container issue was a problem. at the time I didn't know how to fix it, but believe I have a fix for this now. I could prolly turn the feature with fertilized dirt decaying as well.. but I may make the 1.10.2 version defaulted to off, only because ppl wont know whats happening.. but later versions it may be on.

@Syndaryl good idea, but with blocks Im only able to store a max of 16 different states, unless I use tile entities, and Id rather not use a tile entity for this. it will have to just be a random chance, but a really low chance.

**Comment by GenDeathrow** [comment]
also I was so worried about gui and slots I didnt' realize I didn't lock the input and output slots.

**Comment by GenDeathrow** [comment]
I broke this more atm in version 20 because I found a game breaking bug that needed fixing. so atm.. you cant extract anything really.. hopfully I will have another fix tonight to solve this issue

**Comment by GenDeathrow** [comment]
Welp inventory systems don't like restricting specific slots, unless I do something like furnace where it inputs and outputs certain sides to certain slots.  So tomorrows project is that.  its about the best I can do, vanilla hoppers don't play nice. but I need this thing setup to work with hoppers.

**Comment by GenDeathrow** [comment]
This should be fixed with newsiest version 0.3.22
