### ISSUE TITLE
crash open Shredder gui

### ISSUE THREAD

**Issue by TheTestMod** [GenDeathrow/Hatchery#132]
https://pastebin.com/YkV7Wu2v

**Comment by GenDeathrow** [comment]
alright looking into it.. it looks like the wrong import happened. I see about getting a fix out after christmas

**Comment by IamAlathe** [comment]
Yup, I was so excited to try out the shredder, made one, plopped it down game crashed (sometimes my mouse double clicks on its own).  Reboot, pick up some feathers, click the shredder, crash. 

"The game crashed whilst unexpected error
Error: java.lang.NoClassDefFoundError: scala/actors/threadpool/Arrays"

**Comment by GenDeathrow** [comment]
Should be fixed in version 2.0.2.. will be up shortly on curse. Sorry for the late fix, a windows update messed up everything. so at least its fixed now.

**Comment by IamAlathe** [comment]
It does appear to be fixed.  Now that we can access the machines, is it intentional that items cannot be shift-clicked out of them?  Shift clicking actually sends items to input or upgrade slots if they exist or that item is usable (feather fibers will go into the input slot to be processed into feather meal, if it is not already occupied by feathers.  Lucky eggs will go into the upgrade slot.)

**Comment by GenDeathrow** [comment]
Strange, I thought I had actually fixed that issue. I will look into that. With all the small changes to 1.12 I had to rewrite some of this stuff and the inventories have been kinda dick to me.

**Comment by IamAlathe** [comment]
Totally understandable.  Thanks for all your hard work. :)  This is an awesome mod.
