### ISSUE TITLE
Conversion bug with Refined Storage exporters

### ISSUE THREAD

**Issue by Dreytac** [GenDeathrow/Hatchery#147]
Putting a Refined Storage exporter on a chest, filtering with any Hatchery egg and setting "Compare ore dictionary" to "Yes" will export normal eggs as the filtered Hatchery egg allowing conversion from ordinary egg into whatever Hatchery egg you're filtering on.

Screenshots attached.

1. Refined Storage inventory showing normal egg count.
2. Refined Storage exporter showing export of cactus green eggs with "Compare ore dictionary" set to "Yes".
3. Chest inventory showing cactus green eggs being exported.
4. Refined Storage inventory showing egg count is decreasing.

![1 refined storage inventory](https://user-images.githubusercontent.com/861156/37858806-2733ab26-2f56-11e8-82e8-952c683d3d48.png)
![2 refined storage exporter](https://user-images.githubusercontent.com/861156/37858807-27646d92-2f56-11e8-8bf7-fa4aa6fb7861.png)
![3 chest inventory](https://user-images.githubusercontent.com/861156/37858808-27950164-2f56-11e8-9184-de5474fc8fc1.png)
![4 refined storage inventory](https://user-images.githubusercontent.com/861156/37858809-27c2b960-2f56-11e8-976f-788c14d6f44f.png)

Using Minecraft v1.12.1, Hatchery v2.1.2, Chickens v6.0.4 and Refined Storage v1.5.31.

**Comment by GenDeathrow** [comment]
Correct me if I'm wrong. Your saying that you can turn a minecraft egg into any hatchery egg you want because of the ore dictionary setting and an exporter? If that's the case shouldn't this be reported to RS? I don't know enough about RS base code to know whats going on. But it seems like an issue on RS or a combined issue between the mods. 

 As far as hatchery is concerned those are two completely different items. and I don't do any kind of conversions my side. 

Now was this done inside a creative world where you were able to only put in minecraft eggs and get hatchery eggs out? Or is the a survival world?

**Comment by raoulvdberge** [comment]
Not a hatchery issue

**Comment by Dreytac** [comment]
That's a good point. I've cross-posted the issue.

Upon more testing, I'm pretty sure raoulvdberge is right. It seems it might be an issue with a combination of Compact Drawers, Refined Storage and Hatchery.
