### ISSUE TITLE
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes

### ISSUE THREAD

**Issue by JoeSGT** [GenDeathrow/Hatchery#157]
Forge: 1.12.2-14.23.4.2705
hatchery: 1.12.2-2.1.2
https://pastebin.com/raw/LySERhQr

how to reproduce this error:
1) Get a animal net's 
2) Use the animal nets to catch a chicken
3)  then use a storage base mod like Iron Chest mod and use a shulker box 
4) open the shulker box and place 2 row of animal nets stack of 16 of them
5) once your done then grab one of the stack and spread it cross the shulker box you will get an error here an example GIF on how i manage to do this 
https://gyazo.com/bad297dd3c90f1a4552ca978116a82d0

**Comment by JoeSGT** [comment]
I know the GIF i provided earlier is not legitimate in gameplay but here More information i know of to help debug this issue now it seem that it's only happening with IronChest mod links about the mod can be found here with this mod installed with Hatchery mod you can
It seem this issue happen when you put the animal net's that has the chicken in them into an _Iron Shulker box_ from IronChest mod having about 3 stacks of 16 of them and take 1 spread them around causing this crash this should NOT be happening 

https://minecraft.curseforge.com/projects/iron-chests

**Comment by JoeSGT** [comment]
https://i.gyazo.com/8223481c852657a8acd7fff8fdb5d70c.mp4
here a video on how to do it

**Comment by GenDeathrow** [comment]
Not much I can do about that nets contain an entire entity saved in them so there are just too many for mine crafts packet handler to handle.  But I dont ever remember allowing animal nets stack with entities saved in to them.  They only are suppose to stack when empty.

**Comment by JoeSGT** [comment]
https://github.com/GenDeathrow/Hatchery/blob/master/src/main/java/com/gendeathrow/hatchery/item/AnimalNet.java#L35

I think that line right there is override everything but i do see what your saying about it should stack when it's empty but that not working, also would it be possible to just send less data ?

**Comment by GenDeathrow** [comment]
The line you marked is correct, but the items should still not stack because of the nbt data added. It would only stack if the nbt data is the exact same. That should not happen cause each chicken captured will contain different data. 

I cant really send less data cause that's not how that works. Items are updated on server and client. To my knowledge this has never happened with any other storage. and that data is basically handled by the storage. Does this happen in any other inventory like players / regular chest? That would just narrow it down to a single mod. Does this happen with say golden lasso's from extra utils? If it doesn't I can look into what they are doing, but I think I'm doing close to the same thing. 

Also did you capture each chicken? how did you get the nets with chickens in it?

**Comment by JoeSGT** [comment]
okay after testing, i can do the same with Lasso, i also went to the extreme with animal net's and was only able to create this error only with iron chest mod, any shulker box in general any shulker box that in iron chest mod here is few image that i went to the extreme https://gyazo.com/331688d0400872d3856498fc41b8f18e
https://gyazo.com/9d49a9e9df6c21d96b95fa0c8916ae9c
as you see just a normal crystal chest that error don't happen and normal minecraft chest and vanilla shulker this does not happen this help indicate that it's any shulker that in iron chest mod the error happen on both  lasso and animal net's. I am unsure who at fault here

**Comment by GenDeathrow** [comment]
Well I would assume the chest mod would be it. Especially if you cant recreate it in vanilla chest.  Since two separate mods mine and extra utils are crashing in the same mod I would report to them.
