### ISSUE TITLE
chickens self breeding in a single nesting pen?

### ISSUE THREAD

**Issue by popps73x** [GenDeathrow/Hatchery#158]
chickens 6.1.0
hatchery 2.1.2
more chickens 3.2.0

the recipe for refined iron chickens (tech reborn) in the pack is iron+iron however I am getting random refined iron eggs from my iron chicken even though there is no other pen adjacent to it.  I assume this is unintended and may never have been seen before as self breeding would normally assume the same child? any thoughts would be welcome.  :)  thanks

**Comment by GenDeathrow** [comment]
Its sort of intended, but also unintended when dealing with modded chickens. the way the hatchery nest works is when its a single pen there a greatly reduced chance for an egg to drop, I think I had a config % for it (so in theory setting to 0 will make no eggs happen). But they way it works in the code. Is a chicken breeds with it self (for ease of code purpose). Hatchery isn't completely going realistic by any means. I mean Hatchery is more or less meant for vanilla chickens, but has support for Chickens mod. This mod was written for SF3 originally for just the egg nest.  And So because of how my mod works and how the Chickens mod works. This will happen. I appreciate ya bringing it to attention anyways. Thanks
