### ISSUE TITLE
Nest Render issue

### ISSUE THREAD

**Issue by Dexterlounge** [GenDeathrow/Hatchery#168]
Whenever I try putting an Chickens mod egg in a nest, game crashes...

I tried, "going barebone" making a build with just Chicken and Hatchery in 1.12.2 with forge 14.23.5.2768 and still no luck, game crashes every time.

https://gist.github.com/GenDeathrow/3f6d317635fe7294d2478b940c740ff1

**Comment by GenDeathrow** [comment]
Forge has made some changes to the rendering stuff. it broke some mods. I thought they had fixed it. but looks like I have some stuff still on my end to go thur. I look into it

**Comment by DeltaNedas** [comment]
Issue replicated with latest version of Forge.
I could not replicate the issue with forge 14.23.4.2759, use that as a temporary fix.
![screenshot_20181007_135514](https://user-images.githubusercontent.com/39013340/46581993-a0d39400-ca38-11e8-89d5-1400989de7d9.png)
Here's my success story :)

**Comment by GenDeathrow** [comment]
The first issue was fixed in 58.. guess it was still working in 59, broke after that again. I think I have a fix for it. but I have to update 3 mods.. chickens, morechickens, and hatchery before I can fix it. Updated most last night and now I have to do the testing to make sure everything is working. Thanks for keeping me updated. and all the feed back. It helps alot.

**Comment by Dexterlounge** [comment]
No, Thank you for making this awesome mod and all your hard work... It's work like yours, that elevate the Minecraft experience, and keeps it being fun. =)

**Comment by GenDeathrow** [comment]
Newest version(Hatchery v2.1.4) should have fixed these issues. If anything else comes up. I'll reopen.

**Comment by Dexterlounge** [comment]
Sweet! I'll Check it out. Cheers =)
