### ISSUE TITLE
Saving NBT Crash w/ Zoology

### ISSUE THREAD

**Issue by WenXin20** [GenDeathrow/Hatchery#20]
I got a crash with the Zoology Mod.
Forge 2151
Zoology v1.0.1
Hatchery v0.1.12
[Crash Log](http://pastebin.com/20B04Srw)

**Comment by GenDeathrow** [comment]
The Crash is happening inside Zoology.  I report the Issue to them link it here. You didn't really explain what happened. So from what I can tell I'm guessing when the chicken spawned from an egg that you threw, and it crashed?  Zoology throws a crash when something doesn't get initialized on their side.  

All I did was spawn an entity, After that it looks like something happened on their end. Now if I need to add something to make their code work I will. 

`        	HatcheryEggThrown entityegg = new HatcheryEggThrown(worldIn, playerIn, itemStackIn);
            entityegg.setHeadingFromThrower(playerIn, playerIn.rotationPitch, playerIn.rotationYaw, 0.0F, 1.5F, 1.0F);
            worldIn.spawnEntityInWorld(entityegg);`

**Comment by WenXin20** [comment]
I didn't throw an egg, but I did have a baby chicken in the hatchery, maybe it grew up when I wasn't looking?

**Comment by GenDeathrow** [comment]
nvm I looked at it wrong.. my nesting pen created the egg, but still seems to be an issue with zoology still.  I'm trying to read nbt data about the entity thats stored in the hatchery egg it  copied to get its color(only works for chickens mod atm), but zoology is getting null pointer because part of their code doesn't get triggered since the entity isn't created yet. Its just an egg. I really don't see what I can do to fix the issue. If they didn't cause  a fatal error I believe everything would work.

**Comment by hron84** [comment]
@GenDeathrow a quick workaround that comes into my mind (if zoology can't fix their side) is adding a static color table for non-standard chickens. Chickens less likely change their color (they are definitely opposite of chameleons), so this should work.

**Comment by GenDeathrow** [comment]
I technically have a static table for colors. But its not a color thing from what I can tell, their code assumes the chicken is added to the world and crashes out.  Or at least thats what I could tell. I didn't have much time to look at the code.

**Comment by hron84** [comment]
Ohh, it's an @RWTema mod! He's a helpful person, I think if I summon him he will help you figure out what's happening.
