### ISSUE TITLE
IllegalArgumentException: PropertyDirection block=minecraft:air

### ISSUE THREAD

**Issue by Gamewalker** [GenDeathrow/Hatchery#29]
Hey, another one we already got a few times now:

https://www.hastebin.com/anilatucev.sql

This only crashes the client (Its really interesting because only 2 of 6 Players get this sometimes)

**Comment by GenDeathrow** [comment]
ok this makes me think something is interfering with Hatchery now, and not technically a hatchery issue.  the renderer knows a tile entity is there but than only finds air..  that doesn't make sense.. 

https://github.com/GenDeathrow/Hatchery/blob/master/src/main/java/com/gendeathrow/hatchery/block/nestpen/NestPenTileEntityRenderer.java#L27

there should be block there and a block state, because the tile entity exists.  And apparently has a chicken.

**Comment by Gamewalker** [comment]
yeah I have optifine and foamfix (anarchy) running, this could explain this error (but not the other one I think?)

**Comment by GenDeathrow** [comment]
Optifine.. I bets thats it. I know foamfix works fin with hatchery. Id wonder if Optifine and foamfix are having issues  with each other. Just because foamfix mods clears unused rendering stuff out of ram.  Optifine also doesn't work entirely great with all mods either. It was originally for vanilla.  If anything Id remove Optifine, and try it again for a while. After that you can put optifine back in remove foam fix, and than remove both. but Id get a couple hours of play time before  coming to a conculsion.

**Comment by Gamewalker** [comment]
Yeah I will tell my people, I dont get the crash :) I will write again if I know more

**Comment by Gamewalker** [comment]
Happened again and I know what we did. I was watching the nesting pen and my friend destroyed it and the moment the items dropped, I crashed with the error. Dunno if this only happens with opti/foam

**Comment by GenDeathrow** [comment]
I will see about adding a check in to make sure the block is there, just in case.

**Comment by Gamewalker** [comment]
Are you on gitter or some platform? Would be nice if you could tell me how to get chickens as dependency into intellij to play around.

**Comment by GenDeathrow** [comment]
I use the Curse client.

**Comment by GenDeathrow** [comment]
ok so I finally got another report of this. Im going to try and add in a catch to prevent this on the next update. I  think whats happening is that when the block is destroyed like you had said,  the client is still trying to render it that split sec thinking its still there. and its because of the way I check for the facing of the block to place the chicken in the pen for rendering. So now it will make sure the correct block is there. I still couldn't recreate this so I cant properly test to make sure it works.

**Comment by Gamewalker** [comment]
usually we get this if we die and press respawn, if you realease an update
or send me a test version, we can test it

2016-12-31 3:37 GMT+01:00 GenDeathrow <notifications@github.com>:

**Comment by GenDeathrow** [comment]
should be fixed with latest update if not I will reopen

**Comment by Dijkstra1** [comment]
So do not know if sky factory is using the latest version of your mod but the jar says hatchery-1.10.2-0.2.2, got it when respawning a few times now no optifine the pack does foamfix and betterfps

**Comment by Gamewalker** [comment]
0.2.5 is the newest version, I dont know what version fixed it for me, but one did.

**Comment by GenDeathrow** [comment]
@Dijkstra1 it has been fixed in 0.2.5 fixed, a new skyfactory update is scheduled to be out this week with this update. If you can't wait,than you can manually update for now.  Ive known others that have done it without problems.

**Comment by Dijkstra1** [comment]
I would and may still do so but what you got to understand if I need to give everyone on the server fair warning before I do anything like that

**Comment by GenDeathrow** [comment]
well like I said SF3 update should be out this week I believe. At least I know Tuesday was my cutoff date for any updates.

**Comment by GenDeathrow** [comment]
I believe darkosto said they new update will be under the beta tag in curse tomorrow.
