### ISSUE TITLE
Config Option to Require Rooster for Breeding

### ISSUE THREAD

**Issue by Exsolutus** [GenDeathrow/Hatchery#59]
Just a thought I had while working on my modpack. I would love to have a config option for requiring the rooster for chicken breeding. This would disable vanilla chicken+chicken mating and simply require the rooster to do the job.

Making it a config option would, as with all things (IMO), be best to allow maximum user customization.

**Comment by GenDeathrow** [comment]
Thats not a bad idea.. will only work with vanilla chickens though. But I like it

**Comment by Exsolutus** [comment]
Sounds good. I'm curious though, why would it only work with vanilla chickens? Since you're already changing the way breeding works for all chickens which inherit from vanilla chickens, correct? Or is that what you mean?

**Comment by GenDeathrow** [comment]
Ok so the chickens mod that has cross breeding mechanics that wont work, but a rooster can still breed with. Basically all a rooster does in code is makes the chicken breed with its self.this makes it able to breed with any chicken techncally, but wont allow special cross breeding rules. Its really the only way to make it work via code. now it may work just finewith most mod.. just some mechanics wont work correctly. 

And since the chickens mod is dependent on cross breeding it breaks the whole mod.

**Comment by Exsolutus** [comment]
Ah, I see. I'm more interested in the Wild Chickens from Improving Minecraft, mentioned over in Issue #10 
Regardless, cheers on the quick feature addition
