### ISSUE TITLE
EnderIO Farming Station does not hoe fertilized dirt

### ISSUE THREAD

**Issue by KodiakJak** [GenDeathrow/Hatchery#60]
Not sure if this is a Hatchery or EnderIO issue but the EnderIO Farming Station does not hoe fertilized dirt and it must be hoe'd by hand. I had an unbreakable Mattock in the EnderIO Farming Station.

SkyFactory 3.0.6

hatchery-1.10.2-0.2.7

Thanks!

**Comment by GenDeathrow** [comment]
That's because it looks only for vanilla dirt last I checked. But with that said, even if they looked for an instance of dirt, I didn't extend off dirt because of how dirt is codded. Technically I cant do anything about that, but it would have to be changes on both side for it to work properly, I believe.
