### ISSUE TITLE
Nesting Pen not collecting chicken specific drops

### ISSUE THREAD

**Issue by jethrobyte** [GenDeathrow/Hatchery#89]
Running v0.3.11 on SF3 server v3.0.10 beta from Twitch/Curse client.

Myself and others have issues with the nesting pens not collecting chicken specific drops.  I have a Smart Chicken and a Flint chicken in pens, and the manure, feathers and breeding eggs with stats are all successfully being piped out into a chest.  However, in my example, normal eggs and flint are appearing all around the general area of the pens.  

Screenshot of my setup, and drops on the floor:  http://imgur.com/a/gJBTU

Have tried different chests, there are no filters on the pipes (transfer pipes and nodes from Extra Utilities 2).  No changes made to server config that I am aware.

**Comment by GenDeathrow** [comment]
you ruining on a sponge server?

**Comment by jethrobyte** [comment]
Pretty darn sure.  I'm not the server admin, but I'm getting "yes" from several people that have been on the server longer than I have.

**Comment by GenDeathrow** [comment]
its a sponge forge issue. they aren't using proper forge hooks with captured drops. Their is not much I can do for it. Its been brought up on their issue tracker many times. I thought they had fixed it already.

**Comment by GenDeathrow** [comment]
https://github.com/SpongePowered/SpongeForge/issues/1398

**Comment by SpartanSamuel** [comment]
I don't think it's a sponge issue as the server I'm on isn't sponge, just a regular forge server. We have this exact issue.

**Comment by ktole1999** [comment]
only real test would be hatchery and forge server. this would rule out any other mod. then add 1 by 1 to find culprit

**Comment by SpartanSamuel** [comment]
You're right in that it's not any of the core mods from Hatchery and the two Chickens down to Ender IO even. Works on just those in an SP world, so it must be something else causing the issue...

**Comment by SpartanSamuel** [comment]
Once I discovered it wasn't any of the core mods mentioned I haven't performed any further testing. The modpack that this issue is present in contains 231 mods and I've not the patience to run that gauntlet. As far as I understand, there's nothing wrong with Chickens, Hatchery, or the conduits I used from Ender IO. Something else must have interfered with their functioning to have caused items to pop out like they did.

**Comment by macks2008** [comment]
I was just about to report this one again. Glad I used the search bar instead. So it's a Sponge issue? great... as if they weren't slow enough fixing issues. Then again, it might help if they didn't break so many things in the first place

**Comment by GenDeathrow** [comment]
Yeah it is a sponge issue, Forge has a special handler for drops, and sponge is bypassing it with their system. But personally if they are trying to make it work for both forge and vanilla, they should use proper methods provided by forge. I get not many ppl use the system like I do. but to be compatable  with multiple mods without having to support each mod, and make sure any updates don't break it. than using forges built in method is the best option.

**Comment by macks2008** [comment]
I'm going to test again with the latest development build of sponge. I've been needing to set up a test environment for another server issue anyway. If they still haven't fixed this issue I'm going to start getting a bit more aggressive with them, because this is making a major feature of your mod virtually unusable, or at least not without something like an Ender IO vacuum chest.

**Comment by GenDeathrow** [comment]
Sounds good cant wait for the update, and I agree with ya macks it does break a major feature of my mod. And has been very irritating.

**Comment by macks2008** [comment]
I just brought it up again to the folks on Sponge's discord server. I'm now waiting for a reply.

**Comment by GenDeathrow** [comment]
cool keep me update @macks2008

**Comment by macks2008** [comment]
@GenDeathrow On an unrelated note, I'm trying to find the issue in which I said the methane digester was missing a recipe and you said otherwise. I wanted to tell you: I found the recipe after updating the mod. Not sure if it was there in the version I was playing before, but if it was, I might've missed it because there are apparently 2 items from your mod named "methane digester", only one of which has a recipe.

**Comment by jkiejr** [comment]
any update on this, it is very frustrating. what is there discord i cant seem to find it, maybe i can help pester

**Comment by macks2008** [comment]
@jkiejr https://discord.gg/PtaGRAs just don't get yourself banned for pestering too much or anything :-)
generally though, (and while I can't speak for the other  sponge team leaders) Bloodshot is fairly lenient about people bugging them (at least in my experience). Maybe he realizes there ARE a lot of annoying bugs, even if being reminded about them gets beyond the point of "preaching to the choir"?

**Comment by GenDeathrow** [comment]
Im just closing this issue for now... clearing out stuff..
