### ISSUE TITLE
(Suggestion) add a FullInventory State that causes nesting pens to stop any further processing updates

### ISSUE THREAD

**Issue by mahldcat** [GenDeathrow/Hatchery#94]
I was told the behavior of the nesting pens was such that they still process the results from the chickens in them even when their internal inventory was still full?  

Was thinking that it might be useful to have a state to explicitly track this, so that instead the pens go "dormant"?   (thinking of a server setup).

Use case:
* Setup is a series of nesting pens (2-4 per chicken type) x 30-40 chickens.
* These pens are in a chunk loaded area.  
* The pens are free standing and require a player to extract their items. 

In this setup each of the pens would still be processing their chickens even if they fill.  I would <very> much like to avoid the wrath of the server admin with this setup.

**Comment by GenDeathrow** [comment]
I get what you mean about the server issues. but the processing is dealing with the entity in the pen.  If I stop that processing it may cause some unforeseen issue because the chicken needs ticking. 
The processing is better than having the same amount of entities running around, as pens don't process AI or gravity. 
I've had profiles with the same amount of chickens you have and the they normally did not cause the most amount of lag. 
But no matter if I stop them or not, you will still get lag with a lot of tile entities.

**Comment by ktole1999** [comment]
so then how do you avoid the excess tile entities say for instance if your storage is full or jammed they will start spewing items all over the surface. if this is a chunkloaded area this is havoc. if the connecting inventory does not recieve the item then void it.

**Comment by GenDeathrow** [comment]
They wont throw items all over the ground because excess items get deleted. Unless its a sponge server, because sponge is not handling forges captured drops properly.
